---
# List of hosts in YAML format
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# We are using this new format
#
# We are also using ansible-vault to encrypt the value for ansible_sudo_password
# https://docs.ansible.com/ansible/2.5/user_guide/vault.html#use-encrypt-string-to-create-encrypted-variables-to-embed-in-yaml
#
# Use the following command to generate the ansible_sudo_password
#
# ansible-vault encrypt_string --stdin-name 'ansible_sudo_pass'
#
# - Provide a password for your vault (then confirm).  You will need to
#   remember this password every time you run your playbook.  You can make the
#   vault password the same as your sudo password if you like
# - Type in the sudo password for your server identified in the host, then enter
# - Ctrl-D (to exit)
# - Cut and paste the output to the vars section below (see example)

# hosts in the `sovereign` group  use vars defined in `group_vars/sovereign`
# put your host's IP address or domain name below

sovereign:
  hosts:
    #host.example.net
  vars:
    domain: (required)              # domain.com
    main_user_name: (required)      # one word like "admin" or "tech" or "deploy"
    organization: (required)        # Name of Organization
    ansible_sudo_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64313764613531316134626364663330643661396137613737333833303633663330323233613132
          3563623566393239646139653334393863366564623534360a393834323138343964303238323462
          36373035373866333063343464666235326561313162333439326130373739303333336439653134
          3733633163613864360a336665333639616162646538666463616337623665343337373634393433
          6562
