---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart ntp
  service: name=ntp state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart unbound
  service: name=unbound state=restarted

- name: restart mariadb
  service: name=mysql state=restarted

- name: restart ufw
  service: name=ufw state=restarted
