- name: Determine whether roundcube is configured
  stat: path=/var/www/roundcube/config.inc.php
  register: roundcube_config

- name: Install roundcube dependencies (PHP 7.x)
  apt: pkg={{ item }} state=present
  with_items:
    - php
    - php-sqlite
    - php-mcrypt
    - php-gd
    - php-pspell
    - php-intl
    - php-curl
    - php-mbstring
    - php-dom
    - aspell
    - aspell-en
  tags:
    - dependencies

- name: Get Composer installer
  get_url: url=https://getcomposer.org/installer
           dest=/tmp/composer-installer

- name: Copy composer configuration
  copy: src=var_www_roundcube_composer.json dest=/var/www/roundcube/composer.json
    owner=root
    group=www-data
    mode=0644

- name: Install Composer
  command: php /tmp/composer-installer
           chdir=/tmp

- name: Move Composer to global path
  command: mv /tmp/composer.phar /usr/local/bin/composer

- name: Clone roundcube
  git: repo=https://github.com/roundcube/roundcubemail.git
       dest=/var/www/roundcube
       version={{ webmail_version }}
       update=no
       accept_hostkey=yes

- name: Create composer directory
  file:
    path: /var/www/roundcube/vendor
    state: directory
    mode: 0777

- name: Change mode of /var/www/roundcube folder
  file:
    path: /var/www/roundcube
    mode: 0777

- name: Initialize composer
  command: composer install --no-dev
           chdir=/var/www/roundcube
           creates=/var/www/roundcube/vendor/autoload.php
  become: no

- name: Remove installer directory
  file: path=/var/www/roundcube/installer state=absent

- name: Install Roundcube configuration
  template: src=var_www_roundcube_config_config.inc.j2 dest=/var/www/roundcube/config/config.inc.php

- name: Create db directory
  file: path=/decrypted/roundcube group=www-data mode=0775 state=directory

- name: Make logs and temp directories writable by web server
  file: path=/var/www/roundcube/{{ item }} mode=0775 state=directory
  with_items:
    - temp
    - logs

- name: Make roundcube directory accessible to web server
  file: path=/var/www/roundcube group=www-data recurse=yes state=directory

- name: Install sieve plugin configuration
  copy: src=var_www_roundcube_plugins_managesieve_config.inc.php
    dest=/var/www/roundcube/plugins/managesieve/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Install global sieve
  copy: src=var_www_roundcube_config_global.sieve
    dest=/var/www/roundcube/config/global.sieve
    owner=root
    group=www-data
    mode=0644

- name: Create carddav directory
  file:
    path: /var/www/roundcube/plugins/carddav
    state: directory
    mode: 0777

- name: Install carddav plugin configuration
  copy: src=var_www_roundcube_plugins_carddav_config.inc.php
    dest=/var/www/roundcube/plugins/carddav/config.inc.php
    owner=root
    group=www-data
    mode=0644

#- name: Install Google 2-factor authentication plugin configuration
#  copy: src=var_www_roundcube_plugins_twofactor_gauthenticator_config.inc.php
#    dest=/var/www/roundcube/plugins/twofactor_gauthenticator/config.inc.php
#    owner=root
#    group=www-data
#    mode=0644

- name: Configure Apache for Roundcube
  template: src=etc_apache2_sites-available_roundcube.j2
    dest=/etc/apache2/sites-available/roundcube.conf
    group=root owner=root force=yes

- name: Enable Roundcube site
  command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
  notify: restart apache
