- name: Add group name ssl-cert for SSL certificates
  group:
    name: ssl-cert
    state: present

- name: Enable Debian 9 "Stretch" backports repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present
    update_cache: yes

- name: Install certbot
  apt:
    pkg: "{{ item }}"
    state: present
  default_release: stretch-backports
  with_items:
    - certbot
    - python-certbot-apache

- name: Stop web server
  service:
    name: httpd
    state: stopped

- name: Run certbot
  command: certbot certonly --standalone -d {{ domain }} -d {{ inventory_hostname }}
  become: true

- name: Start web server
  service:
    name: httpd
    state: started

#- name: Add cron job for certbot renewal (if configured).
#  cron:
#    name: Certbot automatic renewal.
#    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
#    minute: "{{ certbot_auto_renew_minute }}"
#    hour: "{{ certbot_auto_renew_hour }}"
#    user: "{{ certbot_auto_renew_user }}"




### Back to normal
